//General
export const GET_ERRORS = 'GET_ERRORS';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';

// Asset
export const GET_ASSETS = 'GET_ASSETS';
export const DELETE_ASSET = 'DELETE_ASSET';
export const ADD_ASSET = 'ADD_ASSET';
export const EDIT_ASSET = 'EDIT_ASSET';

// Project
export const GET_PROJECTS = 'GET_PROJECTS';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const ADD_PROJECT = 'ADD_PROJECT';
export const EDIT_PROJECT = 'EDIT_PROJECT';

export const ADD_ACTIVE_PROJECT = 'ADD_ACTIVE_PROJECT'
export const EDIT_ACTIVE_PROJECT = 'EDIT_ACTIVE_PROJECT'
export const GET_ACTIVE_PROJECTS = 'GET_ACTIVE_PROJECTS'

// Requirement
export const GET_REQUIREMENTS = 'GET_REQUIREMENTS';
export const DELETE_REQUIREMENT = 'DELETE_REQUIREMENT';
export const ADD_REQUIREMENT = 'ADD_REQUIREMENT';
export const EDIT_REQUIREMENT = 'EDIT_REQUIREMENT';

// Sentence
export const GET_SENTENCES = 'GET_SENTENCES';
export const DELETE_SENTENCE = 'DELETE_SENTENCE';
export const ADD_SENTENCE = 'ADD_SENTENCE';
export const EDIT_SENTENCE = 'EDIT_SENTENCE';

// Word
export const GET_WORDS = 'GET_WORDS';
export const DELETE_WORD = 'DELETE_WORD';
export const ADD_WORD = 'ADD_WORD';
export const EDIT_WORD = 'EDIT_WORD';

// Component
export const GET_COMPONENTS = 'GET_COMPONENTS';
export const DELETE_COMPONENT = 'DELETE_COMPONENT';
export const ADD_COMPONENT = 'ADD_COMPONENT';
export const EDIT_COMPONENT = 'EDIT_COMPONENT';
export const GET_COMPONENTS_COST_BY_ID = 'GET_COMPONENTS_COST_BY_ID';

// Relation
export const GET_RELATIONS = 'GET_RELATIONS';
export const DELETE_RELATION = 'DELETE_RELATION';
export const ADD_RELATION = 'ADD_RELATION';
export const EDIT_RELATION = 'EDIT_RELATION';

// Task
export const GET_TASKS = 'GET_TASKS';
export const DELETE_TASK = 'DELETE_TASK';
export const ADD_TASK = 'ADD_TASK';
export const EDIT_TASK = 'EDIT_TASK';

// AJAX Utility
export const GET_RELATED_COMPONENTS_FROM_PROJECT = 'GET_RELATED_COMPONENTS_FROM_PROJECT';
export const GET_RELATED_COMPONENTS_FROM_DOWNSHIFT = 'GET_RELATED_COMPONENTS_FROM_DOWNSHIFT';
export const GET_FILTERED_COMPONENTS_AUTOCOMPLETE_SUGGESTION = 'GET_FILTERED_COMPONENTS_AUTOCOMPLETE_SUGGESTION';
export const SAVE_BUTTON_COMPONENT_WIZARD = 'SAVE_BUTTON_COMPONENT_WIZARD';
export const SUBMIT_REQUIREMENT = 'SUBMIT_REQUIREMENT';
export const SUBMIT_TASK = 'SUBMIT_TASK';
export const EDIT_WORD_IN_SENTENCE = 'EDIT_WORD_IN_SENTENCE';
export const EDIT_REQ_PRIORITY_AFTER_EFFECT = 'EDIT_REQ_PRIORITY_AFTER_EFFECT';
export const EDIT_COMPONENT_AFTER_EFFECT = 'EDIT_COMPONENT_AFTER_EFFECT';
export const GET_PROJECT_EFFORT_AND_COST = 'GET_PROJECT_EFFORT_AND_COST';
export const GET_ALL_RELATED_ASSETS = 'GET_ALL_RELATED_ASSETS';
export const GET_RELATED_ASSET_FROM_PROJECT = 'GET_RELATED_ASSET_FROM_PROJECT';
export const GET_ASSET_TEXT_WITH_NO_RELATED_PROJECT = 'GET_ASSET_TEXT_WITH_NO_RELATED_PROJECT';
export const GET_OPEN_TASKS = 'GET_OPEN_TASKS';
export const GET_EXISTING_COMPONENTS_WITH_SAME_NAME = 'GET_EXISTING_COMPONENTS_WITH_SAME_NAME';
export const EXTRACT_TEXT = 'EXTRACT_TEXT';
export const EMPTY_SRL = 'EMPTY_SRL';
export const GET_WEB_INFORMATION = 'GET_WEB_INFORMATION';
export const GET_NLI_RESULTS = 'GET_NLI_RESULTS';
